// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN8lRez6mHX3wgdqak4XQDG17DA3SpD9k',
    appId: '1:391253135490:web:1a2b668515639dfa3ce49b',
    messagingSenderId: '391253135490',
    projectId: 'acadify-uiecc',
    authDomain: 'acadify-uiecc.firebaseapp.com',
    storageBucket: 'acadify-uiecc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdexJAlEUPk_u2tdnjGYfUN92_8E20gLk',
    appId: '1:391253135490:android:ec59f6097f4828c73ce49b',
    messagingSenderId: '391253135490',
    projectId: 'acadify-uiecc',
    storageBucket: 'acadify-uiecc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd-08xpbuhfjCzTL-28VG4mYw7wEgOmKU',
    appId: '1:391253135490:ios:e714664a9b82ef2f3ce49b',
    messagingSenderId: '391253135490',
    projectId: 'acadify-uiecc',
    storageBucket: 'acadify-uiecc.firebasestorage.app',
    iosBundleId: 'com.codify.acadify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDN8lRez6mHX3wgdqak4XQDG17DA3SpD9k',
    appId: '1:391253135490:web:90a7f2f74c2ddaff3ce49b',
    messagingSenderId: '391253135490',
    projectId: 'acadify-uiecc',
    authDomain: 'acadify-uiecc.firebaseapp.com',
    storageBucket: 'acadify-uiecc.firebasestorage.app',
  );
}
